### ISSUE TITLE
301 Redirect auf die SSL-Variante der Webseite setzen

### ISSUE THREAD

**Issue by iblech** [luga-ev/website#10]
Müsste mit folgendem Eintrag funktionieren:

```
<VirtualHost *:80>
    ServerName www.luga.de
    ServerAdmin webmaster@luga.de
    Redirect permanent / https://www.luga.de/
</VirtualHost>
```

Wir könnten uns sogar überlegen, HSTS zu aktivieren, wenn wir der automatischen Zertifikatserneuerung von LetsEncrypt hinreichend vertrauen.

**Comment by joerg-lehmann** [comment]
Erledigt.
