### ISSUE TITLE
Design der alte LIT Seiten ist kaputt

### ISSUE THREAD

**Issue by michael-hartmann** [luga-ev/website#8]
Die Vortragsseite der alten Seiten für den Linux Infotag sind kaputt.

**Comment by micrones** [comment]
Hallo Michael,

kapiere ich grade nicht. Welche alte Seite ist kaputt?

Michael

Am 13.10.2016 um 20:05 schrieb Michael Hartmann:

**Comment by michael-hartmann** [comment]
Die Vortragsseiten, z.B. http://luga.de/Aktionen/LIT-2015/Programm/.

**Comment by iblech** [comment]
Meinst du, dass das CSS fehlt?

**Comment by michael-hartmann** [comment]
Ja.
